### ISSUE TITLE
tabline_z empty in config but flashing workspace name

### ISSUE THREAD

**Issue by jamesredwards** [michaelbrusegard/tabline.wez#36] opened 2024-10-05 21:39 UTC
Have overridden the default config to use ```tabline_z = {}``` but it flashes the current workspace name on and off very quickly (assume in line with the status update in the default config). if i change this to ```'datetime'``` or something else it does the same. can't seem to fix. any advice?

**Comment by michaelbrusegard** [comment] 2024-10-05 23:17
I am unable to reproduce this. Are you on the latest version of the plugin?

This is my config, but with `tabline_z = {}` and it seems to work:
```lua
  tabline.setup({
    options = {
      theme = 'Catppuccin Mocha',
      section_separators = {
        left = wezterm.nerdfonts.ple_right_half_circle_thick,
        right = wezterm.nerdfonts.ple_left_half_circle_thick,
      },
      component_separators = {
        left = wezterm.nerdfonts.ple_right_half_circle_thin,
        right = wezterm.nerdfonts.ple_left_half_circle_thin,
      },
      tab_separators = {
        left = wezterm.nerdfonts.ple_right_half_circle_thick,
        right = wezterm.nerdfonts.ple_left_half_circle_thick,
      },
    },
    sections = {
      tabline_a = {
        { 'mode', fmt = string.lower },
      },
      tab_active = {
        { Attribute = { Intensity = 'Bold' } },
        { Foreground = { Color = colors.ansi[6] } },
        'index',
        'ResetAttributes',
        { Foreground = { Color = colors.foreground } },
        { 'parent', padding = 0 },
        '/',
        { Attribute = { Intensity = 'Bold' } },
        { 'cwd', padding = { left = 0, right = 1 } },
        { 'zoomed', padding = 0 },
      },
      tab_inactive = { 'index', { 'process', icons_only = true, padding = 0 } },
      tabline_x = {},
      tabline_y = { 'ram', 'cpu' },
      tabline_z = {},
    },
    extensions = {
      'resurrect',
      'smart_workspace_switcher',
      'quick_domains',
      'presentation',
    },
  })
```

**Comment by jamesredwards** [comment] 2024-10-06 20:18
Hi thanks for response. yes using most recent version. have changed the status_update_interval to 50000 to stop it annoying me for now. will do some more investigation

**Comment by michaelbrusegard** [comment] 2024-10-18 00:54
I will close this for now as I think this is not a bug with the plugin. Maybe reopen if we can have a reproducable example

**Closed by michaelbrusegard** 2024-10-18 00:54 UTC
